##
## Makefile for graoom in /home/rannou_s/Work/graoom
## 
## Made by Sebastien Rannou
## Login   <rannou_s@epitech.net>
## 
## Started on  Wed Jul  1 22:38:14 2009 Sebastien Rannou
## Last update Wed Jul  1 22:46:20 2009 Sebastien Rannou
##

include ../Makefile.inc

# There's probably a cleaner way to do this

all:
	$(MAKE) -C tools $@

clean:
	$(MAKE) -C tools $@

fclean:
	$(MAKE) -C tools $@

re:	fclean all
