##
## Makefile for battletrantor in /home/rannou_s/Work/graoom
## 
## Made by Sebastien Rannou
## Login   <rannou_s@epitech.net>
## 
## Started on  Wed Jul  1 22:38:14 2009 Sebastien Rannou
##

include ../Makefile.inc

# There's probably a cleaner way to do this

all:
	$(MAKE) -C tools $@
	$(MAKE) -C sdlconsole $@

clean:
	$(MAKE) -C tools $@
	$(MAKE) -C sdlconsole $@

fclean:
	$(MAKE) -C tools $@
	$(MAKE) -C sdlconsole $@

re:	fclean all
